### ISSUE TITLE
Release new version on VSCode marketplace

### ISSUE THREAD

**Issue by rhoriguchi** [mariatsji/ormolu-vscode#12]
This project is in a strange state in your [CHANGELOG.md](https://github.com/mariatsji/ormolu-vscode/blob/master/CHANGELOG.md) it's version 0.0.6, in the [VSCode marketplace](https://marketplace.visualstudio.com/items?itemName=brettm12345.nixfmt-vscode) it's version 0.0.1 and and in the [VSCode marketplace changelog](https://marketplace.visualstudio.com/items/brettm12345.nixfmt-vscode/changelog) it's version 0.0.4.

**Comment by mariatsji** [comment]
Weird, this seems to be in order now though in both [marketplace](https://marketplace.visualstudio.com/items?itemName=sjurmillidahl.ormolu-vscode) and the [changelog](https://marketplace.visualstudio.com/items/sjurmillidahl.ormolu-vscode/changelog)

**Comment by rhoriguchi** [comment]
Thank you
